name: phpapp
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - phpappnet

  db:
    container_name: db
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - phpappnet

volumes:
  db_data:

networks:
  phpappnet:
